name: app

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "8080:80"
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      aggregator:
        condition: service_started

  consumer:
    build:
      context: ./consumer
      no_cache: true
    networks:
      - network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '1.0'


  producer1:
    build:
      context: ./producer
      no_cache: true
    env_file: ./producer.env
    environment:
      - PRODUCER_ID=1
      - REQUEST_ATTEMPTS=10
      - SEND_URL=http://nginx/send
      - FINISH_URL=http://nginx/finish
    networks:
      - network
    depends_on:
      nginx:
        condition: service_started

  producer2:
    build:
      context: ./producer
      no_cache: true
    env_file: ./producer.env
    environment:
      - PRODUCER_ID=2
      - REQUEST_ATTEMPTS=10
      - SEND_URL=http://nginx/send
      - FINISH_URL=http://nginx/finish
    networks:
      - network
    depends_on:
      nginx:
        condition: service_started

  aggregator:
    build:
      context: ./aggregator
      no_cache: true
    networks:
      - network
    depends_on:
      consumer:
        condition: service_healthy

networks:
  network: